# Generated by Django 3.0.4 on 2020-03-17 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('bio', models.TextField(max_length=250, verbose_name='Short Bio')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Note')),
            ],
        ),
    ]
