# Generated by Django 3.0.4 on 2020-03-17 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_composer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('color', models.CharField(choices=[('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('deep-purple', 'Deep-Purple'), ('indigo', 'Indigo'), ('blue', 'Blue'), ('light-blue', 'Light Blue'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('green', 'Green'), ('light-green', 'Light-Green'), ('lime', 'Lime'), ('yellow', 'Yellow'), ('amber', 'Amber'), ('orange', 'Orange'), ('deep-orange', 'Deep Orange'), ('brown', 'Brown'), ('grey', 'Grey'), ('blue-grey', 'Blue Grey'), ('black', 'Black'), ('white', 'White')], default='red', max_length=11, verbose_name='Color')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Note')),
            ],
        ),
        migrations.DeleteModel(
            name='Composer',
        ),
    ]
