# Generated by Django 3.0.4 on 2020-03-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pictures',
            field=models.ManyToManyField(to='main_app.Picture'),
        ),
    ]
