# Generated by Django 3.0.4 on 2020-03-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_note_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='link',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2016/05/25/17/44/background-1415494_960_720.jpg', max_length=500, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='default', max_length=200, verbose_name='Name'),
        ),
    ]
