# Generated by Django 3.0.4 on 2020-03-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_picture_desctiption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='desctiption',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='picture',
            name='link',
            field=models.CharField(max_length=500, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
