# Generated by Django 3.0.4 on 2020-03-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_picture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='background',
            field=models.TextField(default='NONE', max_length=1000),
        ),
    ]
