# Generated by Django 3.0.4 on 2020-03-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200319_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='desctiption',
            new_name='description',
        ),
    ]
