# Generated by Django 3.0.4 on 2020-03-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200320_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='user',
        ),
    ]
